version: '3.7'

services:
  app:
    container_name: aise_app
    build: ./app
    command: sh -c "/code/app/scripts/run_app.sh"
    restart: unless-stopped
    environment:
      PROJECT_NAME: ${APP_PROJECT_NAME}
    ports:
      - "9090:80"
    networks:
      - aise

networks:
  aise:
    driver: bridge
