version: '3.7'

services:
  app:
    container_name: aise_app
    build: ./app
    command: sh -c "/code/app/scripts/run_app.sh"
    restart: unless-stopped
    environment:
      APP_PROJECT_NAME: ${APP_PROJECT_NAME}
      AUDIO_RATE: ${AUDIO_RATE}
    volumes:
      - ./app/system-static/speechbrain:/code/app/system-static/speechbrain
    ports:
      - "9090:80"
    networks:
      - aise

  client:
    container_name: aise_client
    build: ./client
    command: sh -c "/code/client/run_client.sh"
    restart: unless-stopped
    environment:
      API_RECOGNITION_URI: "http://app/api/recognize/"
      API_ENHANCEMENT_URI: "http://app/api/enhancement/"
      AUDIO_RATE: ${AUDIO_RATE}
    ports:
      - "8000:8501"
    networks:
      - aise

networks:
  aise:
    driver: bridge
