name: test_project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements-dev.txt
      - name: Set necessary env variables
          run: export APP_PROJECT_NAME='AI Software Engineering'
      - name: Test with pytest
        run: pytest
